# Generated by Django 5.2 on 2025-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finshed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
