# Generated by Django 5.2 on 2025-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_deadline_alter_todo_finshed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="finshed_at",
        ),
        migrations.AddField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(verbose_name="Data de entrega"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
    ]
