# Generated by Django 5.2 on 2025-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_remove_todo_finshed_at_todo_finished_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(verbose_name="Deadline"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
    ]
